name:        org-db
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Org-mode parser and data drier

ghc-options:
   - -Wall
   - -Wno-missing-home-modules
   - -fprof-auto

dependencies:
  - base >= 4.5
  - bytestring
  - containers
  - filepath
  - hashable
  - lens
  - flatparse
  - flatparse-util
  - mtl
  - split
  - sqlite-simple
  - text
  - time

library:
  source-dirs: src
  exposed-modules:
    - Org.Db
  dependencies:
    - org-types
    - org-parse
    - org-print
